FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# MajesticThai

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/dishes]

### List All Dishes [GET]

+ Response 200 (application/json)

         [
            {
                _id: "58162affe5ef25000341587e",
                category: "sidesandextras",
                item: "Side of Steamed Vegetables",
                price: "3.95",
                description: "Marinated vegetables with our very own special Majestic sauce"
            },
            {
                _id: "58162affe5ef25000341587d",
                category: "sidesandextras",
                item: "Side of Fried Rice",
                price: "5.95",
                description: "Must be orded with a main course"
            },
            {
                _id: "58162affe5ef25000341587c",
                category: "soupsandsalads",
                item: "Tom-Yum_Goong",
                price: "12.95",
                description: "Thai spicy shrip soup wiht lemon grass, lime juice, chili paste, cilantro, red onion and mushroom"
            },
            {
                _id: "58162affe5ef25000341587b",
                category: "soupsandsalads",
                item: "Minced Chicken Salad (Larb)",
                price: "10.95",
                description: "Minced chicken tossed with lime juice, chili paste, onion, basil leaf, roasted rice powder, cilantro, and mixed greens"
            },
            {
                _id: "58162affe5ef25000341587a",
                category: "entrees",
                item: "Pad See-U",
                price: "10.95",
                description: "Stir-fried broad noodle with egg, broccoli and carrot in delicious sweet-garlic sauce"
            },
            {
                _id: "58162affe5ef250003415879",
                category: "entrees",
                item: "Yellow Curry",
                price: "11.95",
                description: "Thai yellow curry cooked in cream of coconut with potato, sweet potato, pinapple and onion"
            },
            {
                _id: "58162affe5ef250003415878",
                category: "entrees",
                item: "Basil Duck",
                price: "17.95",
                description: "Semi-crispy dusk stir-fried in spicy basil sauce with sweet basil, fresh chili, garlic, onion, green beans, and bell pepper"
            },
            {
                _id: "58162affe5ef250003415877",
                category: "appetizer",
                item: "Shrimp in blanket",
                price: "7.95",
                description: "Marinated shrimps wrapped in flour sheet and deep-fired served with sweet & sour sauce"
            },
            {
                _id: "58162affe5ef250003415876",
                category: "appetizer",
                item: "Satay Chicken",
                price: "7.95",
                description: "Chicken on skewers marinated ins pecial Thai Seasoning and grilled to perfections: served with peanut sauce and cucumber salad"
            },
            {
                _id: "58162affe5ef250003415875",
                category: "appetizer",
                item: "Spring Rolls",
                price: "4.95",
                description: "Crispy vegetarian deep-fried spring rolls served with Thai sweet & sour sauce."
            }
        ]
        
## Dish Collection [/dishes/:id]

    + Parameters 

        + id (number) - ID of the dish in the form of an integer


### List Single Dish [GET]

+ Response 200 (application/json)

        {
        _id: "58162affe5ef250003415878",
        category: "entrees",
        item: "Basil Duck",
        price: "17.95",
        description: "Semi-crispy dusk stir-fried in spicy basil sauce with sweet basil, fresh chili, garlic, onion, green beans, and bell pepper"
        }
        
## Order Collection [/orders]

### List Orders [GET]

+ Response 200 (application/json)


        [
            {
            "order_id": "1",
            "username": "frazierr2",
            "time": "1:30",
            "total": 15.90,
            "items": [
              {
                _id: "58162affe5ef250003415877",
                category: "appetizer",
                item: "Shrimp in blanket",
                price: "7.95",
                description: "Marinated shrimps wrapped in flour sheet and deep-fired served with sweet & sour sauce"
            },
            {
                _id: "58162affe5ef250003415876",
                category: "appetizer",
                item: "Satay Chicken",
                price: "7.95",
                description: "Chicken on skewers marinated ins pecial Thai Seasoning and grilled to perfections: served with peanut sauce and cucumber salad"
            },
             ]
            },
            {
            "order_id": "2",
            "username": "frazierr2",
            "time": "10:30",
            "total": 29.90,
            "items": [
                {
                _id: "58162affe5ef250003415879",
                category: "entrees",
                item: "Yellow Curry",
                price: "11.95",
                description: "Thai yellow curry cooked in cream of coconut with potato, sweet potato, pinapple and onion"
            },
            {
                _id: "58162affe5ef250003415878",
                category: "entrees",
                item: "Basil Duck",
                price: "17.95",
                description: "Semi-crispy dusk stir-fried in spicy basil sauce with sweet basil, fresh chili, garlic, onion, green beans, and bell pepper"
            },
             ]
            }
        ]
        
## Order [/orders/{id}]

+ Parameters 
    + id (number) - ID of the order in the form of an integer

### List Order [GET]

+ Response 200 (application/json)

        {
            "order_id": "2",
            "username": "frazierr2",
            "time": "10:30",
            "total": 29.90,
            "items": [
                {
                _id: "58162affe5ef250003415879",
                category: "entrees",
                item: "Yellow Curry",
                price: "11.95",
                description: "Thai yellow curry cooked in cream of coconut with potato, sweet potato, pinapple and onion"
            },
            {
                _id: "58162affe5ef250003415878",
                category: "entrees",
                item: "Basil Duck",
                price: "17.95",
                description: "Semi-crispy dusk stir-fried in spicy basil sauce with sweet basil, fresh chili, garlic, onion, green beans, and bell pepper"
            },
             ]
        }